### ISSUE TITLE
Endpoint error on 1.13

### ISSUE THREAD

**Issue by ghost** [Razikus/TotallyMCRestApi#2]
Issue when calling the endpoint on 1.13

Callback:
```
  {
    "callback": {
      "CLASSNAME": "eu.razniewski.totallymcrestapi.commandCallback.OutputConfigCommandCallback",
      "DATA": {
        "command": "time set 1000",
        "additionalParams": {}
      }
    },
    "route": "/timeday",
    "requestType": "GET",
    "tokenEnabled": false,
    "tokens": []
  },
```

Console log:
```
10:54:21 AM TotallyMCRestApi: GET Callback /timeday executed from 127.0.0.1
10:54:21 AM CONSOLE: WARN]: java.lang.IllegalStateException: Asynchronous command dispatch!
10:54:21 AM CONSOLE: WARN]: at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:14)
10:54:21 AM CONSOLE: WARN]: at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:697)
10:54:21 AM CONSOLE: WARN]: at eu.razniewski.totallymcrestapi.commandCallback.OutputConfigCommandCallback.callWithParams(OutputConfigCommandCallback.java:59)
10:54:21 AM CONSOLE: WARN]: at eu.razniewski.totallymcrestapi.SparkIntegrator.lambda$fromEntryPoint$0(SparkIntegrator.java:56)
10:54:21 AM CONSOLE: WARN]: at spark.ResponseTransformerRouteImpl$1.handle(ResponseTransformerRouteImpl.java:47)
10:54:21 AM CONSOLE: WARN]: at spark.http.matching.Routes.execute(Routes.java:61)
10:54:21 AM CONSOLE: WARN]: at spark.http.matching.MatcherFilter.doFilter(MatcherFilter.java:130)
10:54:21 AM CONSOLE: WARN]: at spark.embeddedserver.jetty.JettyHandler.doHandle(JettyHandler.java:50)
10:54:21 AM CONSOLE: WARN]: at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1568)
10:54:21 AM CONSOLE: WARN]: at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
10:54:21 AM CONSOLE: WARN]: at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
10:54:21 AM CONSOLE: WARN]: at org.eclipse.jetty.server.Server.handle(Server.java:531)
10:54:21 AM CONSOLE: WARN]: at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:352)
10:54:21 AM CONSOLE: WARN]: at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:260)
10:54:21 AM CONSOLE: WARN]: at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:281)
10:54:21 AM CONSOLE: WARN]: at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:102)
10:54:21 AM CONSOLE: WARN]: at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)
10:54:21 AM CONSOLE: WARN]: at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:762)
10:54:21 AM CONSOLE: WARN]: at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:680)
10:54:21 AM CONSOLE: WARN]: at java.lang.Thread.run(Unknown Source)
```

**Version of plugin:**
- 0.2

**Version of minecraft server:**
- 1.13

**Additional context**
Happy to help debug. The command also does not get executed on the server. I am using the ```time set 1000``` command as its a simple command to test! Other endpoints and commands also not working. Only inbuilt classes work (such as playersonline etc.)

**Comment by Razikus** [comment]
Hi!
Try to change OutputConfigCommandCallback to VoidConfigCommandCallback and check if everything is OK
OutputConfigCommandCallback is needed to get also return of command

Btw - I will check that on 1.13

**Comment by ghost** [comment]
Can confirm that changing to ```VoidConfigCommandCallback``` does not work either. Although there is no error dumped, the command is also not sent to the console and in this instance, the time is not set either.

Thanks for the quick response too! - When fixed, beer shall be sent ;)

**Comment by ghost** [comment]
Tested on 1.12 and works - must be 1.13 issue. Not sure if I can help any further?

**Comment by Razikus** [comment]
If you can give me more time in the day :D...
I will try to check & fix it today later

Sorry for waiting, but work etc

**Comment by Razikus** [comment]
Hi, fixed in version 0.3 
[Here](https://github.com/Razikus/TotallyMCRestApi/releases/tag/0.3)

Please confirm, that it works for you

Greetings

**Comment by ghost** [comment]
Tested today - works perfectly.

Sending beer (aka coffee)....  👍

**Comment by Razikus** [comment]
Thanks a lot!
Much appreciated - issue closed!
